Repository LandlordPlugin/LandLord, pull requests merged in 2021-07, with the labels that each got.

#16 Feature: improve claim management
  LandLord-api/src/main/java/biz/princeps/landlord/api/AMultiTask.java
  LandLord-api/src/main/java/biz/princeps/landlord/api/ClearType.java
  LandLord-api/src/main/java/biz/princeps/landlord/api/ILandLord.java
  LandLord-api/src/main/java/biz/princeps/landlord/api/IMultiTask.java
  LandLord-api/src/main/java/biz/princeps/landlord/api/IMultiTaskManager.java
  LandLord-api/src/main/java/biz/princeps/landlord/api/ManageMode.java
  LandLord-core/src/main/java/biz/princeps/landlord/ALandLord.java
  LandLord-core/src/main/java/biz/princeps/landlord/commands/Landlordbase.java
  LandLord-core/src/main/java/biz/princeps/landlord/commands/admin/Clear.java
  LandLord-core/src/main/java/biz/princeps/landlord/commands/admin/GiveClaims.java
  LandLord-core/src/main/java/biz/princeps/landlord/commands/claiming/Claim.java
  LandLord-core/src/main/java/biz/princeps/landlord/commands/claiming/Claims.java
  LandLord-core/src/main/java/biz/princeps/landlord/commands/claiming/MultiClaim.java
  LandLord-core/src/main/java/biz/princeps/landlord/commands/claiming/MultiUnclaim.java
  LandLord-core/src/main/java/biz/princeps/landlord/commands/claiming/Unclaim.java
  LandLord-core/src/main/java/biz/princeps/landlord/commands/claiming/UnclaimAll.java
  LandLord-core/src/main/java/biz/princeps/landlord/commands/friends/MultiAddfriend.java
  LandLord-core/src/main/java/biz/princeps/landlord/commands/friends/MultiRemovefriend.java
  LandLord-core/src/main/java/biz/princeps/landlord/commands/management/Borders.java
  LandLord-core/src/main/java/biz/princeps/landlord/commands/management/ListLands.java
  LandLord-core/src/main/java/biz/princeps/landlord/commands/management/Manage.java
  LandLord-core/src/main/java/biz/princeps/landlord/commands/management/ManageAll.java
  LandLord-core/src/main/java/biz/princeps/landlord/commands/management/MultiListLands.java
  LandLord-core/src/main/java/biz/princeps/landlord/commands/management/MultiManage.java
  LandLord-core/src/main/java/biz/princeps/landlord/guis/AManage.java
  LandLord-core/src/main/java/biz/princeps/landlord/guis/ClearGUI.java
  LandLord-core/src/main/java/biz/princeps/landlord/guis/ManageGui.java
  LandLord-core/src/main/java/biz/princeps/landlord/guis/ManageGuiAll.java
  LandLord-core/src/main/java/biz/princeps/landlord/integrations/Towny.java
  LandLord-core/src/main/java/biz/princeps/landlord/listener/MapListener.java
  LandLord-core/src/main/java/biz/princeps/landlord/listener/SecureWorldListener.java
  LandLord-core/src/main/java/biz/princeps/landlord/manager/DelimitationManager.java
  LandLord-core/src/main/java/biz/princeps/landlord/manager/LPlayerManager.java
  LandLord-core/src/main/java/biz/princeps/landlord/manager/VaultManager.java
  LandLord-core/src/main/java/biz/princeps/landlord/manager/map/LandMap.java
  LandLord-core/src/main/java/biz/princeps/landlord/multi/MultiClaimTask.java
  LandLord-core/src/main/java/biz/princeps/landlord/multi/MultiClearTask.java
  LandLord-core/src/main/java/biz/princeps/landlord/multi/MultiMode.java
  LandLord-core/src/main/java/biz/princeps/landlord/multi/MultiTaskManager.java
  LandLord-core/src/main/java/biz/princeps/landlord/multi/MultiUnclaimTask.java
  LandLord-core/src/main/java/biz/princeps/landlord/placeholderapi/LLExpansion.java
  LandLord-core/src/main/java/biz/princeps/landlord/protection/AWorldGuardManager.java
  LandLord-core/src/main/java/biz/princeps/landlord/protection/LandCache.java
  LandLord-core/src/main/java/biz/princeps/landlord/util/ConfigUtil.java
  LandLord-core/src/main/java/biz/princeps/landlord/util/Skulls.java
  LandLord-core/src/main/java/biz/princeps/lib/command/CommandManager.java
  LandLord-core/src/main/java/biz/princeps/lib/crossversion/MaterialProxy.java
  LandLord-core/src/main/java/biz/princeps/lib/crossversion/Stuff.java
  LandLord-core/src/main/java/biz/princeps/lib/gui/simple/AbstractGUI.java
  LandLord-core/src/main/java/biz/princeps/lib/storage/Datastorage.java
  LandLord-core/src/main/java/biz/princeps/lib/util/CommandDelayManager.java
  LandLord-latest/src/main/java/biz/princeps/landlord/LandLord.java
  LandLord-latest/src/main/java/biz/princeps/landlord/OwnedLand.java
  LandLord-latest/src/main/java/biz/princeps/landlord/manager/MobsManager.java
  LandLord-latest/src/main/java/biz/princeps/landlord/manager/WorldGuardManager.java
  LandLord-legacy/src/main/java/biz/princeps/landlord/LandLord.java
  LandLord-legacy/src/main/java/biz/princeps/landlord/OwnedLand.java
  LandLord-legacy/src/main/java/biz/princeps/landlord/manager/MobManager.java
  LandLord-legacy/src/main/java/biz/princeps/landlord/manager/WorldGuardManager.java
  buildSrc/src/main/kotlin/biz.princeps.java-conventions.gradle.kts
Labels: enhancement, size: large

#19 Feature/fix placeholders
  LandLord-core/src/main/java/biz/princeps/landlord/placeholderapi/LLExpansion.java
Labels: bug

#25 Feature/small cleanup
  LandLord-api/src/main/java/biz/princeps/landlord/api/IOwnedLand.java
  LandLord-api/src/main/java/biz/princeps/landlord/api/IRegenerationManager.java
  LandLord-api/src/main/java/biz/princeps/landlord/api/IWorldGuardManager.java
  LandLord-core/src/main/java/biz/princeps/landlord/commands/Landlordbase.java
  LandLord-core/src/main/java/biz/princeps/landlord/commands/management/Borders.java
  LandLord-core/src/main/java/biz/princeps/landlord/commands/management/ListLands.java
  LandLord-core/src/main/java/biz/princeps/landlord/commands/management/MultiListLands.java
  LandLord-core/src/main/java/biz/princeps/landlord/commands/management/borders/Borders.java
  LandLord-core/src/main/java/biz/princeps/landlord/commands/management/borders/BordersTask.java
  LandLord-core/src/main/java/biz/princeps/landlord/listener/MapListener.java
  LandLord-core/src/main/java/biz/princeps/landlord/manager/map/LandMap.java
  LandLord-core/src/main/java/biz/princeps/landlord/protection/AOwnedLand.java
  LandLord-core/src/main/java/biz/princeps/landlord/protection/AWorldGuardManager.java
  LandLord-core/src/main/java/biz/princeps/landlord/protection/LandCache.java
  LandLord-core/src/main/java/biz/princeps/lib/chat/ConfirmationDialog.java
  LandLord-core/src/main/java/biz/princeps/lib/storage/Datastorage.java
  LandLord-latest/src/main/java/biz/princeps/landlord/OwnedLand.java
  LandLord-latest/src/main/java/biz/princeps/landlord/listener/WGRegenListener.java
  LandLord-latest/src/main/java/biz/princeps/landlord/manager/MaterialsManager.java
  LandLord-latest/src/main/java/biz/princeps/landlord/manager/MobsManager.java
  LandLord-latest/src/main/java/biz/princeps/landlord/manager/WorldGuardManager.java
  LandLord-latest/src/main/resources/config.yml
  LandLord-legacy/src/main/java/biz/princeps/landlord/OwnedLand.java
  LandLord-legacy/src/main/java/biz/princeps/landlord/manager/MobManager.java
  LandLord-legacy/src/main/java/biz/princeps/landlord/manager/WorldGuardManager.java
  README.md
  buildSrc/src/main/kotlin/biz.princeps.java-conventions.gradle.kts
Labels: enhancement, size: medium

#28 Add PR section to contribution
  CONTRIBUTING.md
Labels: documentation
